services:
  linux:
    image: dockurr/vm
    container_name: ubuntu
    environment:
      VERSION: "ubuntu"  # Możesz też wpisać "arch", "fedora", "debian"
      RAM_SIZE: "4G"
      CPU_CORES: "4"
      DISK_SIZE: "36G"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
    stop_grace_period: 2m